name: Build Flutter for Raspberry Pi 5 (Linux ARM64)

on: [push, pull_request]

jobs:
  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Linux Dependencies
        run: sudo apt update && sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev -y

      - name: Enable Flutter Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Create Linux Desktop Files (if missing)
        run: flutter create --platforms=linux .

      - name: Install ARM64 Cross-Compiler
        run: sudo apt install g++-aarch64-linux-gnu -y

      - name: Build for ARM64 (Raspberry Pi 5)
        run: |
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          flutter build linux --release --target-platform linux-arm64

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-build
          path: build/linux/arm64/release/bundle/
